permalink: ':category/:year/:monthName/:slug'
categories:
  - key: 'dev'
    title: 'Dev'
  - key: 'random'
    title: 'Random'
authors:
  - name: 'Author Two'
    avatar: 'assets/media/avatar.png'
    email: 'email@domain.tld'
postPages:
  author: 'Danial Goodwin'
  layout: single
  components:
    - type: pageContent
    - type: taxonomy
      taxonomyType: tags
    - type: taxonomy
      taxonomyType: categories
